# Site settings

# General settings
lang: en
title: Inclusion jekyll theme
email: mail@orlovmax.com
author: Maxim Orlov
description: "Responsive blog theme for jekyll website generator"
keywords: "jekyll theme, jekyll template, responsive jekyll theme"

# URL settings
baseurl: "/jekyll-inclusion" # the subpath of your site, e.g. /blog/
url: "http://website-templates.github.io" # the base hostname & protocol for your site
# lang_en: "http://blog.orlovmax.com"
# lang_ua: "http://uablog.orlovmax.com"
# lang_ru: "http://rublog.orlovmax.com"
home-repo: "https://github.com/website-templates/jekyll-inclusion"
twitter_username: orlovmax_im
github_username:  orlovmax
# fb_username:
gplus_username: 104202961668156466871
# skype_username:
bitbucket_username: orlovmax
# linkedin_username:

# Default src
home_img: "img/bg/index-home.jpg"
end_img: "img/bg/index-end.jpg"
thumb_img: "img/pic.jpg"

# disqus-code:

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "page-:num/"
exclude: [
'node_modules',
'bower_components',
'Gruntfile.js',
'package.json',
'bower.json',
'README.md',
'Rakefile'
]

source: _build
destination: _deploy

# Category pages settings
categories:
  url: /category/
  slug: ''
  title_prefix: 'Category: '
  descr_prefix: 'Blog posts in category «'
  descr_postfix: '», page '
  layout: category.html

# Tag pages settings
tags:
  url: /tag/
  slug: ''
  title_prefix: 'Tag: '
  descr_prefix: 'Posts tagged «'
  descr_postfix: '», page '
  layout: tag.html

# Layout common texts
pager:
  page-next: 'Newer posts ›'
  page-prev: '‹ Older posts'
  post-next: 'Next post ›'
  post-prev: '‹ Previous post'
