# Site settings

# General settings
lang: en
title: Inclusion jekyll theme
email: mail@orlovmax.com
author: Maxim Orlov
description: "Responsive blog theme for jekyll website generator"
keywords: "jekyll theme, jekyll template, responsive jekyll theme"

# URL settings
baseurl: "/jekyll-inclusion" # the subpath of your site, e.g. /blog/
url: "http://website-templates.github.io" # the base hostname & protocol for your site
home-repo: "https://github.com/website-templates/jekyll-inclusion"
twitter_username: orlovmax_im
github_username:  orlovmax
# fb_username:
# vk_username:
gplus_username: 104202961668156466871
# skype_username:
bitbucket_username: orlovmax
# linkedin_username:

# Multilanguage blog settings: names, base url and current lang
# langs:
#   "en": "http://blog.orlovmax.com"
#   "ru": "http://rublog.orlovmax.com"
#   "ua": "http://uablog.orlovmax.com"
# lang_current: "ua"

# Default src
start_img: "img/bg/home_start.jpg"
end_img: "img/bg/home_end.jpg"
thumb_img: "img/pic.jpg"

# disqus-code:

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 3
paginate_path: "page-:num/"
exclude: [
'node_modules',
'bower_components',
'Gruntfile.js',
'package.json',
'bower.json',
'README.md',
'Rakefile'
]

source: _build
destination: _deploy
